# Generated by Django 5.2 on 2025-05-27 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('user', 'Usuario Regular')], default='user', max_length=10),
        ),
        migrations.CreateModel(
            name='Canje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=100)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('puntos', models.IntegerField()),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
