# Generated by Django 5.2 on 2025-06-04 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_role_canje'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialTasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('puntos_por_kilo', models.IntegerField()),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='canje',
            name='comprobante',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/'),
        ),
        migrations.AddField(
            model_name='canje',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='canje',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('completado', 'Completado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='canje',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.materialtasa'),
        ),
        migrations.CreateModel(
            name='RedencionPuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField()),
                ('valor_cop', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('nequi', 'Nequi'), ('daviplata', 'Daviplata'), ('bancolombia', 'Bancolombia')], max_length=20)),
                ('numero_cuenta', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True)),
                ('notas_admin', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
