# Generated by Django 5.2 on 2025-06-04 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_materialtasa_canje_comprobante_canje_notas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password_reset_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
