# Generated by Django 5.2 on 2025-06-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usuario_password_reset_expires_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('barrio', models.CharField(max_length=100)),
                ('referencia', models.TextField(blank=True, null=True)),
                ('direccion', models.CharField(max_length=255)),
            ],
        ),
    ]
