# Generated by Django 5.2 on 2025-06-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_configuracion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracion',
            options={'ordering': ['categoria', 'nombre'], 'verbose_name': 'Configuración', 'verbose_name_plural': 'Configuraciones'},
        ),
        migrations.AddField(
            model_name='configuracion',
            name='categoria',
            field=models.CharField(choices=[('puntos', 'Configuración de Puntos'), ('rutas', 'Configuración de Rutas'), ('materiales', 'Configuración de Materiales'), ('notificaciones', 'Configuración de Notificaciones'), ('general', 'Configuración General')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Texto'), ('numero', 'Número'), ('booleano', 'Booleano'), ('json', 'JSON'), ('lista', 'Lista')], default='texto', max_length=20),
        ),
    ]
