# Generated by Django 5.2 on 2025-07-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_usuario_biografia_usuario_mostrar_puntos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='biografia',
        ),
        migrations.AddField(
            model_name='usuario',
            name='testimonio',
            field=models.TextField(blank=True, null=True, verbose_name='Testimonio'),
        ),
    ]
