# Generated by Django 5.2 on 2025-07-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_usuario_biografia_usuario_testimonio'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='core/img/default_profile.png', null=True, upload_to='fotos_perfil/'),
        ),
    ]
