# Generated by Django 5.2 on 2025-07-10 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def clean_invalid_rutas(apps, schema_editor):
    """
    Elimina las rutas que tienen usuario_id=1 pero no existe el usuario
    """
    Ruta = apps.get_model('core', 'Ruta')
    Usuario = apps.get_model('core', 'Usuario')
    
    # Eliminar rutas con usuario_id=1 si no existe el usuario
    try:
        usuario_1 = Usuario.objects.get(id=1)
    except Usuario.DoesNotExist:
        # Si no existe el usuario con ID=1, eliminar todas las rutas que lo referencian
        Ruta.objects.filter(usuario_id=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_ruta_materiales_ruta_usuario_notificacion'),
    ]

    operations = [
        # Primero ejecutar la función para limpiar datos inválidos
        migrations.RunPython(clean_invalid_rutas, reverse_code=migrations.RunPython.noop),
        
        # Luego aplicar los cambios de la migración 0015 de manera segura
        migrations.AlterField(
            model_name='ruta',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to=settings.AUTH_USER_MODEL),
        ),
    ]
