# Generated by Django 5.2 on 2025-08-05 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_fix_ruta_usuario_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentoAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('url_intento', models.URLField()),
                ('fecha_intento', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Intento de Acceso',
                'verbose_name_plural': 'Intentos de Acceso',
                'ordering': ['-fecha_intento'],
            },
        ),
        migrations.CreateModel(
            name='SesionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_sesion', models.CharField(max_length=255, unique=True)),
                ('dispositivo_id', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('activa', models.BooleanField(default=True)),
                ('ultima_actividad', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Usuario',
                'verbose_name_plural': 'Sesiones de Usuario',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
