# Generated by Django 5.2.1 on 2025-08-06 19:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_intentoacceso_sesionusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('rechazada', 'Rechazada'), ('reagendada', 'Reagendada'), ('completada', 'Completada')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='ruta',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ruta',
            name='fecha_procesamiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='notas_admin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
