# Generated by Django 5.2.1 on 2025-08-06 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_ruta_estado_ruta_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Configuracion',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
