from django.urls import path
from . import views
from .redemptions import get_pending_redemptions, aprobar_redencion, rechazar_redencion

urlpatterns = [
    path('', views.index, name='index'),
    path('logout/', views.logout_view, name='logout'),
    path('registrate/', views.registrate, name='registrate'),
    path('iniciosesion/', views.iniciosesion, name='iniciosesion'),
    path('perfil/', views.perfil, name='perfil'),
    path('categorias/', views.categorias, name='categorias'),
    path('canjes/', views.solicitar_canje, name='solicitar_canje'),
    path('historial/', views.historial, name='historial'),
    path('logros/', views.logros, name='logros'),
    path('sesiones-activas/', views.sesiones_activas, name='sesiones_activas'),
    path('recompensas/', views.recompensas, name='recompensas'),

    path('pagos/', views.pagos, name='pagos'),
    path('usuarioadmin/', views.usuarioadmin, name='usuarioadmin'),
    path('canjeadmin/', views.canjeadmin, name='canjeadmin'),
    path('dashusuario/', views.dashusuario, name='dashusuario'),
    path('paneladmin/', views.paneladmin, name='paneladmin'),
    path('rutas/', views.rutas, name='rutas'),
    path('inicioadmin/', views.inicioadmin, name='inicioadmin'),
    path('redimir-puntos/', views.redimir_puntos, name='redimir_puntos'),
    path('canjes/', views.canjes, name='canjes'),
    path('aprobar-canje/<int:canje_id>/', views.aprobar_canje, name='aprobar_canje'),
    path('recuperar-password/', views.recuperar_password, name='recuperar_password'),
    path('reset-password/<str:token>/', views.reset_password, name='reset_password'),
    path('add_user/', views.add_user, name='add_user'),
    path('edit_user/<int:user_id>/', views.edit_user, name='edit_user'),
    path('delete_user/<int:user_id>/', views.delete_user, name='delete_user'),
    path('add_ruta/', views.add_ruta, name='add_ruta'),
    path('edit_ruta/<int:ruta_id>/', views.edit_ruta, name='edit_ruta'),
    path('delete_ruta/<int:ruta_id>/', views.delete_ruta, name='delete_ruta'),
    path('confirmar_ruta/<int:ruta_id>/', views.confirmar_ruta, name='confirmar_ruta'),
    path('rechazar_ruta/<int:ruta_id>/', views.rechazar_ruta, name='rechazar_ruta'),
    path('reagendar_ruta/<int:ruta_id>/', views.reagendar_ruta, name='reagendar_ruta'),
    path('estadisticasadmin/', views.estadisticasadmin, name='estadisticasadmin'),
    path('alertas/', views.alertas, name='alertas'),
    path('add_alerta/', views.add_alerta, name='add_alerta'),
    path('edit_alerta/', views.edit_alerta, name='edit_alerta'),
    path('delete_alerta/', views.delete_alerta, name='delete_alerta'),

    path('get_dashboard_stats/', views.get_dashboard_stats, name='get_dashboard_stats'),
    path('get-pending-canjes/', views.get_pending_canjes, name='get_pending_canjes'),
    path('get-pending-canjes-admin/', views.get_pending_canjes_for_admin, name='get_pending_canjes_for_admin'),
    path('aprobar_canje_ajax/', views.aprobar_canje_ajax, name='aprobar_canje_ajax'),
    path('get_chart_data/', views.get_chart_data, name='get_chart_data'),
    path('admin/canje/<int:canje_id>/procesar/', views.procesar_canje, name='procesar_canje'),
    path('rutasusuario/', views.rutasusuario, name='rutasusuario'),
    path('agendar_ruta_usuario/', views.agendar_ruta_usuario, name='agendar_ruta_usuario'),
    # Nuevas rutas
    path('ranking/', views.ranking, name='ranking'),
    path('soportusu/', views.soportusu, name='soportusu'),
    path('redimir-puntos/', views.redimir_puntos, name='redimir_puntos'),
    path('admin/redemptions/', get_pending_redemptions, name='get_pending_redemptions'),
    path('admin/redemptions/<int:redencion_id>/approve/', aprobar_redencion, name='aprobar_redencion'),
    path('admin/redemptions/<int:redencion_id>/reject/', rechazar_redencion, name='rechazar_redencion'),
    path('retiroadmin/', views.retiroadmin, name='retiroadmin'),
    # Nuevas rutas para estadísticas avanzadas y seguridad
    path('advanced-statistics/', views.get_advanced_statistics, name='get_advanced_statistics'),
    path('security-analytics/', views.get_security_analytics, name='get_security_analytics'),
    path('export-statistics/', views.export_statistics, name='export_statistics'),
    path('cleanup-sessions/', views.cleanup_expired_sessions, name='cleanup_expired_sessions'),
    path('security-monitor/', views.security_monitor, name='security_monitor'),
    path('force-logout-session/', views.force_logout_session, name='force_logout_session'),
    path('cleanup-sessions-ajax/', views.cleanup_sessions_ajax, name='cleanup_sessions_ajax'),
]

